"""Named values shared by deterministic strategy rules."""

GRADE_A_PLUS_MIN_SCORE = 85
GRADE_A_MIN_SCORE = 75
GRADE_B_MIN_SCORE = 65
GRADE_C_MIN_SCORE = 50

STRATEGY_CACHE_TTL_SECONDS = 60
CANDLE_CACHE_TTL_SECONDS = 15
AI_REPORT_CACHE_TTL_SECONDS = 600
HISTORY_SNAPSHOT_INTERVAL_SECONDS = 900


__all__ = [
    "GRADE_A_PLUS_MIN_SCORE",
    "GRADE_A_MIN_SCORE",
    "GRADE_B_MIN_SCORE",
    "GRADE_C_MIN_SCORE",
    "STRATEGY_CACHE_TTL_SECONDS",
    "CANDLE_CACHE_TTL_SECONDS",
    "AI_REPORT_CACHE_TTL_SECONDS",
    "HISTORY_SNAPSHOT_INTERVAL_SECONDS",
]
